---
format: gfm
bibliography: references.bib
---


# Setup

**Requires R 4.1.0 or newer** We tested our code on R 4.5.1 on Ubuntu Linux 22.04.

There are two ways to manage your R environment so that the correct packages are installed:

- Using an isolated environment with `renv`. We also use this to manage the dependencies for Docker
- Freestyle and use your global environment. All required packages are listed in section "Project Dependencies".

## Environment using renv

### Linux

Ensure `renv` (version >= 1.1.4) and `pak` are installed:

```bash
R -e 'install.packages(c("renv", "pak"))'
```

Then you can activate and restore the environment in R by running:

```r
options(renv.config.pak.enabled = TRUE)
renv::activate()
renv::restore()
```

### Windows

::: {.callout-note}
Although we expect the R scripts in this codebase to work across all platforms, it requires a lot of tooling outside of R (e.g., cURL, make) that is readily available on Unix-like systems. Your milage with Windows will vary and additional tweaking may be required. In case of doubt, we recommend using [Windows Subsystem for Linux](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux).
:::

Ensure `renv` (version >= 1.1.4) and [Rtools](https://cran.r-project.org/bin/windows/Rtools/) are installed.

*Protip:* You can install RTools with winget. Open a PowerShell and enter `winget install rtools`

Installing `renv`:

```bash
R -e 'install.packages("renv")'
```

Then you can activate and restore the environment in R by running:

```r
renv::activate()
renv::restore()
```

### Adding new dependencies

Now all packages should be installed for the virtual environment. If you need to add new dependencies, you can do the following:

```r
pak::pkg_install("<new package dependency")
renv::snapshot()
```

This should update the `renv.lock` file with the new dependencies. Please also add the package you added to the section "Project Dependencies" at the bottom of this readme.

# Studies and Data

All selected studies make the data and source code publicly available. The required data files from each study should be in the `rawdata` directory. Most files can be downloaded automatically by using `make rawdata/<filename>`. For example, to download the text data for @curini:2021:CMU use `make rawdata/zip_texts.rar`.

- @chan:2022:WT: Data and code is available on [OSF](https://osf.io/ycx6j/)
  - Text data: [`rawdata/final_data.RDS`](https://osf.io/3hazf)
- @curini:2021:CMU: Data and code is on [Harvard Dataverse](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/LAXHS3)
  - Text data: [`rawdata/zip_texts.rar`](https://dataverse.harvard.edu/api/access/datafile/4291434)
  - Meta data: [`rawdata/meta_table.tab`](https://dataverse.harvard.edu/api/access/datafile/4291441)
  - Lemmatization model: [`rawdata/italian-isdt-ud-2.5-191206.udpipe`](https://raw.githubusercontent.com/jwijffels/udpipe.models.ud.2.5/master/inst/udpipe-ud-2.5-191206/italian-isdt-ud-2.5-191206.udpipe)
- @czymara:2020:C: Data is available upon request via [GESIS](https://search.gesis.org/research_data/SDN-10.7802-2034?doi=10.7802/2034), source code repository is on [Github](https://github.com/czymara/perceiving-COVID19-in-Germany) and [OSF](https://osf.io/6s7rp/) 
  - Text / survey data: [`Corona-survey_full.dta`](https://search.gesis.org/research_data/SDN-10.7802-2034?doi=10.7802/2034) (You must request it via GESIS BASIS)
  - Stop word list: [`rawdata/stopwords-de.txt`](https://raw.githubusercontent.com/czymara/perceiving-COVID19-in-Germany/refs/heads/master/in/stopwords-de.txt)
  - Lemmatization model: [`rawdata/rawdata/german-gsd-ud-2.5-191206.udpipe`](https://raw.githubusercontent.com/jwijffels/udpipe.models.ud.2.5/master/inst/udpipe-ud-2.5-191206/german-gsd-ud-2.5-191206.udpipe)
- @jankin:2024:W: Data available via [Harvard Dataverse](https://doi.org/10.7910/DVN/0TJX8Y) and code via [PRIO](https://www.prio.org/journals/jpr/replicationdata), see entry at section 2025 (62) Issue 4.
  - Text data: [`rawdata/UNGDC_1946-2024.tar.gz`](https://dataverse.harvard.edu/file.xhtml?fileId=11095259&version=13.0)
  - Meta data: [`rawdata/meta_table.tab`](https://dataverse.harvard.edu/api/access/datafile/4291441)
- @takano:2023:awe: Data and code available via [OSF](https://osf.io/6ktey/)


# Docker

::: {.callout-warning}
Building the docker image can take up to 10 minutes ☠️ ☠️ ☠️
:::

The entire analysis can be run with Docker by using

```bash
docker compose build
docker compose up
```

Note that `docker compose up` currently runs the debug mode of all analysis steps.

# Project Dependencies

Major dependencies are listed below [^1]:

```{r, echo = FALSE, results = "asis"}
rpkgs <- sort(unique(renv::dependencies(quiet = TRUE)$Package))
cat(paste0("```r\nPackages <- c(\n",
           paste(paste0("    \"", rpkgs, "\""),
                 collapse = ",\n"), "\n)\n\npak::pkg_install(packages)\n```\n"))
```

# Options

There are options that one can customize; see `.Rprofile`.

[^1]: There are also additional dependencies for developers: `withr` and `quarto`

# References